// Tests for automation/media/validate-image.js.  Run: node --test automation/media
// All inputs are synthetic FIXTURES (zz-phase7-test-*), generated by make-fixtures.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const { validateImage, sha256Hex, sameSha256, detectFormat } = require("./validate-image.js");

const fixture = (name) => new Uint8Array(readFileSync(join(here, "fixtures", name)));
const LIMIT = { maxBytes: 10 * 1024 * 1024 };
const nodeSha = (b) => createHash("sha256").update(b).digest("hex");

const VALID = [
  ["zz-phase7-test.jpg", "image/jpeg"],
  ["zz-phase7-test.png", "image/png"],
  ["zz-phase7-test-lossy.webp", "image/webp"],
  ["zz-phase7-test-lossless.webp", "image/webp"],
  ["zz-phase7-test.avif", "image/avif"],
];

test("valid JPEG, PNG, WebP (lossy + lossless) and AVIF are accepted with dimensions and hash", () => {
  for (const [name, mime] of VALID) {
    const bytes = fixture(name);
    const r = validateImage(bytes, LIMIT);
    assert.equal(r.valid, true, `${name}: ${r.code} ${r.detail}`);
    assert.equal(r.code, null);
    assert.equal(r.detected_mime_type, mime, name);
    assert.deepEqual([r.width, r.height], [12, 8], name);
    assert.equal(r.file_size, bytes.length);
    assert.equal(r.sha256, nodeSha(bytes));
  }
});

test("sha256Hex matches node:crypto for boundary lengths and a large buffer", () => {
  for (const len of [0, 1, 55, 56, 63, 64, 65, 119, 120, 127, 128, 1000]) {
    const b = new Uint8Array(randomBytes(len));
    assert.equal(sha256Hex(b), nodeSha(b), `len ${len}`);
  }
  const big = new Uint8Array(randomBytes(3 * 1024 * 1024 + 7));
  assert.equal(sha256Hex(big), nodeSha(big));
});

test("sameSha256 accepts hex and base64 forms and refuses mismatches", () => {
  const b = fixture("zz-phase7-test.jpg");
  const hex = nodeSha(b);
  assert.equal(sameSha256(hex, hex.toUpperCase()), true);
  assert.equal(sameSha256(hex, createHash("sha256").update(b).digest("base64")), true);
  assert.equal(sameSha256(hex, nodeSha(fixture("zz-phase7-test.png"))), false);
  assert.equal(sameSha256(hex, "zz"), null);
  assert.equal(sameSha256(hex, undefined), null);
});

test("empty file is rejected", () => {
  assert.equal(validateImage(new Uint8Array(0), LIMIT).code, "empty_file");
  assert.equal(validateImage(null, LIMIT).code, "empty_file");
});

test("oversized file is rejected before parsing; a missing limit is refused", () => {
  const b = fixture("zz-phase7-test.png");
  assert.equal(validateImage(b, { maxBytes: b.length - 1 }).code, "oversized");
  assert.equal(validateImage(b, { maxBytes: b.length }).valid, true);
  assert.equal(validateImage(b, {}).code, "limit_unknown");
});

test("unsupported formats are rejected from the bytes, whatever the declared type", () => {
  assert.equal(validateImage(fixture("zz-phase7-test.gif"), LIMIT).code, "unsupported_format");
  const html = new TextEncoder().encode("<html><script>alert(1)</script></html>");
  assert.equal(validateImage(html, LIMIT).code, "unsupported_format");
  const heic = new Uint8Array(32);
  heic.set([0, 0, 0, 24], 0);
  heic.set(new TextEncoder().encode("ftypheic\0\0\0\0mif1heic"), 4);
  assert.equal(detectFormat(heic), null);
  assert.equal(validateImage(heic, LIMIT).code, "unsupported_format");
  const zip = new Uint8Array([0x50, 0x4b, 0x03, 0x04, 1, 2, 3, 4, 5, 6, 7, 8]);
  assert.equal(validateImage(zip, LIMIT).code, "unsupported_format");
});

test("truncated files of every format are corrupt", () => {
  for (const [name] of VALID) {
    const b = fixture(name);
    const cut = b.subarray(0, Math.floor(b.length * 0.6));
    const r = validateImage(cut, LIMIT);
    assert.equal(r.code, "corrupt_image", `${name}: ${r.code}`);
  }
});

test("bit damage and structural lies are detected", () => {
  const png = fixture("zz-phase7-test.png").slice();
  png[png.length - 20] ^= 0xff; // inside IDAT -> CRC mismatch
  assert.equal(validateImage(png, LIMIT).code, "corrupt_image");

  const jpg = fixture("zz-phase7-test.jpg");
  const noEoi = jpg.slice(0, jpg.length - 2); // drop FF D9
  assert.equal(validateImage(noEoi, LIMIT).code, "corrupt_image");

  const webp = fixture("zz-phase7-test-lossy.webp").slice();
  webp[4] = (webp[4] + 4) & 0xff; // RIFF size no longer matches
  assert.equal(validateImage(webp, LIMIT).code, "corrupt_image");

  const avif = fixture("zz-phase7-test.avif");
  const padded = new Uint8Array(avif.length + 5);
  padded.set(avif);
  assert.equal(validateImage(padded, LIMIT).code, "corrupt_image");

  const pngTail = new Uint8Array(fixture("zz-phase7-test.png").length + 3);
  pngTail.set(fixture("zz-phase7-test.png"));
  assert.equal(validateImage(pngTail, LIMIT).code, "corrupt_image");
});

test("dimension and pixel limits apply", () => {
  const b = fixture("zz-phase7-test.jpg");
  assert.equal(validateImage(b, { ...LIMIT, maxDimension: 10 }).code, "dimensions_out_of_range");
  assert.equal(validateImage(b, { ...LIMIT, maxPixels: 95 }).code, "dimensions_out_of_range");
});

test("a format outside the allowed list is refused even when structurally valid", () => {
  const r = validateImage(fixture("zz-phase7-test.avif"), { ...LIMIT, allowedMimeTypes: ["image/jpeg"] });
  assert.equal(r.code, "mime_not_allowed");
  assert.equal(r.detected_mime_type, "image/avif");
});

test("the n8n Media Processing export embeds this validator verbatim", () => {
  const source = readFileSync(join(here, "validate-image.js"), "utf8");
  const workflow = JSON.parse(readFileSync(join(here, "..", "n8n", "vip-realty-media-processing.json"), "utf8"));
  const codes = workflow.nodes.filter((n) => n.type === "n8n-nodes-base.code").map((n) => n.parameters.jsCode);
  const embedding = codes.filter((c) => c.includes(source));
  assert.ok(embedding.length >= 2, `validator embedded in ${embedding.length} Code nodes`);
});
